import Head from 'next/head'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Haroon's portfolio</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
              <section className=' bg-blue-700 min-h-screen'>
                Hello

              </section>
            </main>
        </div>
    )
}
